myapp2/config/routes.rb
Rails.application.routes.draw do
  get 'case/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   
  resources :case

  post 'case/create'
end

myapp2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp2/app/models/reporter.rb
class Reporter < ApplicationRecord
end

myapp2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myapp2/app/controllers/case_controller.rb
class CaseController < ApplicationController
  def index
    @cases = Reporter.all
  end

 def create
     @case = Reporter.new(case_params)
     @case.save
     redirect_to @case
  end 

  def show
     @case = Reporter.find(params[:id])
  end
  
  def edit
     @case = Reporter.find(params[:id])
  end

  def update 
     @case = Reporter.find(params[:id])
     if @case.update(case_params)
        redirect_to @case
     else
        render 'edit'
     end
  end
  def destroy
     @case = Reporter.find(params[:id])
     @case.destroy
  end
	
  private 
   def case_params
      params.require(:case).permit(:name, :blood_type, :case, :gender)
   end
 
end

myapp2/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp2/app/helpers/case_helper.rb
module CaseHelper
end

myapp2/app/helpers/index_helper.rb
module IndexHelper
end

myapp2/app/views/case/edit.html.erb
<p>Edit Case</p>

<%= form_with(model: @reporter, local: true) do |form|%>

<p>Case Reporter Page</p>

<p>Name:</p>
<p>
<%= form.text_field :name %>
</p>

<p>Case:</p>
<p>
<%= form.text_area :case %>
</p>


<p>Blood Type</p>
<p>
<%= form.radio_button(:blood_type, "A")%>
<%= form.label(:bloodA, "A")%>

<%= form.radio_button(:blood_type, "B")%>
<%= form.label(:bloodB, "B")%>


<%= form.radio_button(:blood_type, "AB")%>
<%= form.label(:bloodAB, "AB")%>


<%= form.radio_button(:blood_type, "O")%>
<%= form.label(:bloodO, "O")%>

</p>

<p>Gender</p>
<p>
<%= form.radio_button(:gender, "Female")%>
<%= form.label(:female, "Female")%>


<%= form.radio_button(:gender, "Male")%>
<%= form.label(:male, "Male")%>

</p>
<p>
   <%= form.submit %>
</p>

<% end %>

myapp2/app/views/case/index.html.erb
<%= form_with scope:
 :case,  url:case_create_path, local: true do |form| %>

<p>Case Reporter Page</p>

<p>Name:</p>
<p>
<%= form.text_field :name %>
</p>

<p>Case:</p>
<p>
<%= form.text_area :case %>
</p>


<p>Blood Type</p>
<p>
<%= form.radio_button(:blood_type, "A")%>
<%= form.label(:bloodA, "A")%>

<%= form.radio_button(:blood_type, "B")%>
<%= form.label(:bloodB, "B")%>


<%= form.radio_button(:blood_type, "AB")%>
<%= form.label(:bloodAB, "AB")%>


<%= form.radio_button(:blood_type, "O")%>
<%= form.label(:bloodO, "O")%>

</p>

<p>Gender</p>
<p>
<%= form.radio_button(:gender, "Female")%>
<%= form.label(:female, "Female")%>


<%= form.radio_button(:gender, "Male")%>
<%= form.label(:male, "Male")%>

</p>
<p>
   <%= form.submit %>
</p>

<% end %>
<div>
 <% @cases.each do |c| %>
    <p><%= c.name %>
    <p><%= c.case %>
    <p><%= c.gender %>
    <p><%= c.blood_type %>
<%= link_to 'Edit', edit_case_path(c) %>
<%= link_to 'Delete', case_path(c), method: 
    :delete, data:{confirm: 'Are you sure?'} %>
<% end %>
<p>
</div>

myapp2/app/views/case/show.html.erb
<p>
  <strong> Story </strong>
</p>

<p>
  <strong><%= @case.name%></strong>


</p>

myapp2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaseReporter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>